/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_Tensosense                     11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_model_number_string            18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_led_control                    27
#define gattdb_report_button                  29
#define gattdb_battery_service                31
#define gattdb_battery_level                  33
#define gattdb_characteristic_presentation_format 34
#define gattdb_automation_io                  35
#define gattdb_analog                         37
#define gattdb_characteristic_user_description 40
#define gattdb_characteristic_extended_properties 41
#define gattdb_value_trigger_setting          42
#define gattdb_time_trigger_setting           43
#define gattdb_valid_range                    44
#define gattdb_ota                            45
#define gattdb_ota_control                    47
#define gattdb_imu_acceleration               50
#define gattdb_imu_orientation                53
#define gattdb_imu_control_point              56


#endif // __GATT_DB_H
