################################################################################
# Automatically-generated file. Do not edit!
################################################################################

S79_SRCS := 
OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S79_UPPER_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
autogen \
gecko_sdk_4.4.2/hardware/board/src \
gecko_sdk_4.4.2/hardware/driver/configuration_over_swo/src \
gecko_sdk_4.4.2/hardware/driver/mx25_flash_shutdown/src/sl_mx25_flash_shutdown_usart \
gecko_sdk_4.4.2/platform/CMSIS/RTOS2/Source \
gecko_sdk_4.4.2/platform/Device/SiliconLabs/EFR32MG24/Source \
gecko_sdk_4.4.2/platform/bootloader/api \
gecko_sdk_4.4.2/platform/bootloader/app_properties \
gecko_sdk_4.4.2/platform/common/src \
gecko_sdk_4.4.2/platform/common/toolchain/src \
gecko_sdk_4.4.2/platform/driver/debug/src \
gecko_sdk_4.4.2/platform/emdrv/dmadrv/src \
gecko_sdk_4.4.2/platform/emdrv/nvm3/src \
gecko_sdk_4.4.2/platform/emlib/src \
gecko_sdk_4.4.2/platform/peripheral/src \
gecko_sdk_4.4.2/platform/radio/rail_lib/plugin/pa-conversions \
gecko_sdk_4.4.2/platform/radio/rail_lib/plugin/rail_util_built_in_phys/efr32xg24 \
gecko_sdk_4.4.2/platform/radio/rail_lib/plugin/rail_util_built_in_phys \
gecko_sdk_4.4.2/platform/radio/rail_lib/plugin/rail_util_power_manager_init \
gecko_sdk_4.4.2/platform/radio/rail_lib/plugin/rail_util_sequencer \
gecko_sdk_4.4.2/platform/security/sl_component/se_manager/src \
gecko_sdk_4.4.2/platform/security/sl_component/sl_mbedtls_support/src \
gecko_sdk_4.4.2/platform/security/sl_component/sl_protocol_crypto/src \
gecko_sdk_4.4.2/platform/security/sl_component/sl_psa_driver/src \
gecko_sdk_4.4.2/platform/service/device_init/src \
gecko_sdk_4.4.2/platform/service/hfxo_manager/src \
gecko_sdk_4.4.2/platform/service/iostream/src \
gecko_sdk_4.4.2/platform/service/power_manager/src \
gecko_sdk_4.4.2/platform/service/sleeptimer/src \
gecko_sdk_4.4.2/platform/service/system/src \
gecko_sdk_4.4.2/platform/service/udelay/src \
gecko_sdk_4.4.2/protocol/bluetooth/src \
gecko_sdk_4.4.2/util/silicon_labs/silabs_core/memory_manager \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/demos/ble/gatt_server \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/demos/ble/mqtt_ble \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/demos/ble/numeric_comparison \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/demos/demo_runner \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/demos/dev_mode_key_provisioning/src \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/demos/network_manager \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/3rdparty/mbedtls_utils \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/3rdparty/tinycbor/src \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/abstractions/pkcs11/corePKCS11/source \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/abstractions/platform/freertos \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/abstractions/secure_sockets/freertos_plus_tcp \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/abstractions/transport/secure_sockets \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/ble/src \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/ble/src/services/data_transfer \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/ble/src/services/device_information \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/ble/src/services/mqtt_ble \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/common \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/common/taskpool \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/https/src \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/serializer/src/cbor \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/c_sdk/standard/serializer/src/json \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/coreHTTP/source \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/coreHTTP/source/dependency/3rdparty/http_parser \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/coreMQTT/source \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/freertos_plus/standard/crypto/src \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/freertos_plus/standard/freertos_plus_cli/source \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/freertos_plus/standard/freertos_plus_posix/source \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/freertos_plus/standard/freertos_plus_tcp \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/freertos_plus/standard/freertos_plus_tcp/portable/BufferManagement \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/freertos_plus/standard/tls/src \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/freertos_plus/standard/utils/src \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/libraries/logging \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/vendors/siliconlabs/boards/all/ports/ble/source \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/vendors/siliconlabs/boards/all/ports/pkcs11 \
gecko_sdk_4.4.2/util/third_party/aws_iot_libs/vendors/siliconlabs/boards/all/ports/wifi \
gecko_sdk_4.4.2/util/third_party/freertos/cmsis/Source \
gecko_sdk_4.4.2/util/third_party/freertos/kernel \
gecko_sdk_4.4.2/util/third_party/freertos/kernel/portable/GCC/ARM_CM33_NTZ/non_secure \
gecko_sdk_4.4.2/util/third_party/freertos/kernel/portable/MemMang \
gecko_sdk_4.4.2/util/third_party/freertos/kernel/portable/SiliconLabs \
gecko_sdk_4.4.2/util/third_party/mbedtls/library \
gecko_sdk_4.4.2/util/third_party/printf \
gecko_sdk_4.4.2/util/third_party/printf/src \
gecko_sdk_4.4.2/util/third_party/segger/systemview/SEGGER \
. \

