/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_Tensosense                     11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_automation_io_real             19
#define gattdb_analog                         21
#define gattdb_characteristic_presentation_format 23
#define gattdb_characteristic_user_description 24
#define gattdb_characteristic_extended_properties 25
#define gattdb_value_trigger_setting          26
#define gattdb_time_trigger_setting           27
#define gattdb_valid_range                    28
#define gattdb_automation_io                  29
#define gattdb_aio_digital_in                 31
#define gattdb_aio_num_of_digitals_in         34
#define gattdb_aio_digital_out                36
#define gattdb_aio_num_of_digitals_out        38
#define gattdb_battery_service                39
#define gattdb_batt_measurement               41
#define gattdb_power_source                   43
#define gattdb_power_source_type              45


#endif // __GATT_DB_H
